swagger: '2.0'
info:
  title: "odin"
  description: |
    ## Endpoints
    ``` bash
      api gateway
      https://odincommunity.api.com
    ```
    ## Métodos
    Suportado os seguintes métodos:
    POST, GET, OPTION, PUT, DELETE
  version: "1.0.0-alpha"
host: 'odincommunity.api.com'
basePath: /
produces:
  - application/json
schemes:
  - https
paths:
  /v1/report:
    post:
      produces:
        - application/json
      description: | 
        Route to create reports

        ```bash
        curl http://localhost:4444/v1/report \
          --include \
          --header "Content-Type: application/json" \
          --request "POST" \
          --data '{
            "loc" : {
              "latitude" : -14.769235,
              "longitude" : -42.657405
            },
            "user": "b6b4d4be-6533-11ee-8c99-0242ac120002",
            "kind": 1,
            "cause": [1],
            "decription": "Foco de incêndio no capinal"
          }'
        ```
      parameters: 
        - in: body
          name: body
          description: ""
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/Report'
      responses:
        '200':
          description: StatusOK
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/Sucess'
        '500':
          description: StatusInternalServerError
  /v1/user/{user}/report/:
    get: 
      produces:
        - application/json
      description: | 
        Route to list all reports by user

        ``` bash
        curl http://localhost:4444/v1/user/b6b4d4be-6533-11ee-8c99-0242ac120002/report \
          --header "Content-Type: application/json" \
          --request "GET"   

        ```
      parameters: 
        - name: "user"
          in: "path"
          description: "user uuid"
          required: true
          type: string
      responses:
        '200':
          description: StatusOK
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/ReportBack'
        '500':
          description: StatusInternalServerError
          
  /v1/fire/:
    get: 
      produces:
        - application/json
      description: | 
        Route to list fires

        ``` bash
          curl http://localhost:4444/v1/fire \   
            --header "Content-Type: application/json" \
            --request "GET"
        ```
      responses:
        '200':
          description: StatusOK
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/Fire'
        '500':
          description: StatusInternalServerError
          
definitions:
  Sucess:
    properties:
      status:
        type: number
        format: integer
        
  Report:
    properties:
      cause:
        type: array
        items:
          type: number
          format: integer
      kind:
        type: number
        format: integer
      user: 
        type: string
      descreption: 
        type: string
      loc:
        type: object
        properties: 
          lat:
            type: number
            format: float
          lng: 
            type: number
            format: float

  ReportBack:
    properties:
      status:
        type: string
      kind:
        type: string
      cause:
        type: string
      user: 
        type: string
      descreption: 
        type: string
      loc:
        type: object
        properties: 
          lat:
            type: number
            format: float
          lng: 
            type: number
            format: float

  Fire:
    properties: 
      dangerousness:
        type: string
      loc:
        type: object
        properties: 
          lat:
            type: number
            format: float
          lng: 
            type: number
            format: float
